### ISSUE TITLE
add funding logos!

### ISSUE THREAD

**Issue by rrohwer** [rrohwer/MyMendota#11]
because the whole point is to emphasize how federal/state grant money is spent, we should acknowledge with a wall of logos at the bottom.  

this should be made as a single png or jpg file that combines them, and the McMahon one (not a pdf or individual image files). 

Then we can add it where the McMahon logo is currently.

**Comment by patriciatran** [comment]
Do you have a list of the funding agencies? I can do it if you provide a list (I can also ask Trina if you don't know all of them)
