### ISSUE TITLE
check colors for colorblind people

### ISSUE THREAD

**Issue by rrohwer** [rrohwer/MyMendota#13]
There are color blind pallets, but we can also just check what we're currently using. Save the image from Rstudio as a png or jpg, and then drag and drop into here: 

http://www.color-blindness.com/coblis-color-blindness-simulator/

I love this site!

**Comment by ingle** [comment]
Currently used colormaps work perfectly fine for all types of colorblind people (deuteranopia, protanopia and tritanopia)
Tested with Color Oracle app. https://colororacle.org/
