### ISSUE TITLE
host under new username for day-of 

### ISSUE THREAD

**Issue by rrohwer** [rrohwer/MyMendota#15]
to make sure we don't run out of our 20hr storage space if staffers all play with it for an hour each lol. but still a lot of people have been using the current one.

**Comment by ingle** [comment]
I'll take care of this tonight, once all the final changes are merged. The short URL (tiny.cc/posdn) will remain the same.

**Comment by ingle** [comment]
tiny.cc/mymendota -> robinrohwer.shinyapps.io/MyMendota

Backup: tiny.cc/posdn -> ingleyahoo.shinyapps.io/MyMendota
