### ISSUE TITLE
add animated secchi disk that moves with the date scrollbar

### ISSUE THREAD

**Issue by rrohwer** [rrohwer/MyMendota#7]
- maybe next to existing secchi plot? Maybe next to boxplot or other summary statistic?

**Comment by patriciatran** [comment]
Added a secchi disk image that moves with Slider selection, and fixed bugs so that when YSI date exist but no secchi data, the plot still shows up.

**Comment by patriciatran** [comment]
Fixed aspect ratio of secchi disk
